### PR TITLE
Create PULL_REQUEST_TEMPLATE.md

### PR DESCRIPTION
**Pull request by rim109**

### CODE REVIEW

**Review by bangjunhee — APPROVED** [review]
LGTM

**Review by YJ9352 — APPROVED** [review]
ok

**Review by tkfkadldy — COMMENTED** [review]
👍

**Review by tkfkadldy — APPROVED** [review]
👍

**Review by YJ9352 — APPROVED** [review]
🌽

**Review by bangjunhee — APPROVED** [review]
LGTM

**Review by tkfkadldy — APPROVED** [review]
:)

**Review by YJ9352 — CHANGES_REQUESTED** [review]
🥕

**Review by YJ9352 — APPROVED** [review]
0000

**Review by YJ9352 — APPROVED** [review]
!!!!!

**Review by bangjunhee — APPROVED** [review]
fgerre

**Review by YJ9352 — APPROVED** [review]
ㅠㅠ

**Pull request closed without merging**
